
package ec.edu.ups.carrito.views;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class EliminarProductoView extends javax.swing.JInternalFrame {

    public EliminarProductoView() {
        initComponents();
    }

    public JTextField getTextFieldCodigoEliminar() {
        return TextFieldCodigoEliminar;
    }

    public void setTextFieldCodigoEliminar(JTextField TextFieldCodigoEliminar) {
        this.TextFieldCodigoEliminar = TextFieldCodigoEliminar;
    }

    public JButton getAceptarEliminar() {
        return AceptarEliminar;
    }

    public void setAceptarEliminar(JButton AceptarEliminar) {
        this.AceptarEliminar = AceptarEliminar;
    }

    public JButton getCancelarEliminar() {
        return CancelarEliminar;
    }

    public void setCancelarEliminar(JButton CancelarEliminar) {    
        this.CancelarEliminar = CancelarEliminar;
    }
    
    public void mostrarInformacion (String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        dispose(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldCodigoEliminar = new javax.swing.JTextField();
        AceptarEliminar = new javax.swing.JButton();
        CancelarEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elimine un producto");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("EliminarProducto");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese el codigo: ");

        TextFieldCodigoEliminar.addActionListener(this::TextFieldCodigoEliminarActionPerformed);

        AceptarEliminar.setText("Buscar");
        AceptarEliminar.addActionListener(this::AceptarEliminarActionPerformed);

        CancelarEliminar.setText("Cancelar");
        CancelarEliminar.addActionListener(this::CancelarEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(AceptarEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarEliminar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarEliminar)
                    .addComponent(CancelarEliminar))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        TextFieldCodigoEliminar.getAccessibleContext().setAccessibleName("TextFieldCodigoEliminar");
        TextFieldCodigoEliminar.getAccessibleContext().setAccessibleDescription("TextFieldCodigoEliminar");
        AceptarEliminar.getAccessibleContext().setAccessibleName("AceptarEliminar");
        CancelarEliminar.getAccessibleContext().setAccessibleName("CancelarEliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCodigoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoEliminarActionPerformed

    private void AceptarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarEliminarActionPerformed
        
    }//GEN-LAST:event_AceptarEliminarActionPerformed

    private void CancelarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarEliminarActionPerformed
        TextFieldCodigoEliminar.setText("");
        dispose();
    }//GEN-LAST:event_CancelarEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarEliminar;
    private javax.swing.JButton CancelarEliminar;
    private javax.swing.JTextField TextFieldCodigoEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
