
package ec.edu.ups.carrito.views;

import ec.edu.ups.carrito.controllers.ProductoController;
import javax.swing.JInternalFrame;

public class PrincipalView extends javax.swing.JFrame {

    private CrearProductoView crearProductoView;
    private ProductoController productoController;
    private BuscarProductoView buscarProductoView;
    private ActualizarProductoView actualizarProductoView;
    private EliminarProductoView eliminarProductoView;
   
    
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        productosMenu = new javax.swing.JMenu();
        CrearProductosMenuItem = new javax.swing.JMenuItem();
        BuscarProductosMenuItem = new javax.swing.JMenuItem();
        EliminarProductosMenuItem = new javax.swing.JMenuItem();
        ActualizarProductosMenuItem = new javax.swing.JMenuItem();
        carritoMenu = new javax.swing.JMenu();
        AgregarCarritoMenuItem = new javax.swing.JMenuItem();
        EliminarCarritoMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setPreferredSize(new java.awt.Dimension(401, 310));
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);
        desktopPane.getAccessibleContext().setAccessibleDescription("");

        productosMenu.setMnemonic('f');
        productosMenu.setText("Productos");

        CrearProductosMenuItem.setMnemonic('o');
        CrearProductosMenuItem.setText("Crear");
        CrearProductosMenuItem.addActionListener(this::CrearProductosMenuItemActionPerformed);
        productosMenu.add(CrearProductosMenuItem);

        BuscarProductosMenuItem.setMnemonic('s');
        BuscarProductosMenuItem.setText("Buscar");
        BuscarProductosMenuItem.addActionListener(this::BuscarProductosMenuItemActionPerformed);
        productosMenu.add(BuscarProductosMenuItem);

        EliminarProductosMenuItem.setMnemonic('a');
        EliminarProductosMenuItem.setText("Eliminar");
        EliminarProductosMenuItem.addActionListener(this::EliminarProductosMenuItemActionPerformed);
        productosMenu.add(EliminarProductosMenuItem);

        ActualizarProductosMenuItem.setMnemonic('x');
        ActualizarProductosMenuItem.setText("Actualizar");
        ActualizarProductosMenuItem.addActionListener(this::ActualizarProductosMenuItemActionPerformed);
        productosMenu.add(ActualizarProductosMenuItem);

        menuBar.add(productosMenu);

        carritoMenu.setMnemonic('e');
        carritoMenu.setText("Carrito");

        AgregarCarritoMenuItem.setMnemonic('t');
        AgregarCarritoMenuItem.setText("Agregar");
        carritoMenu.add(AgregarCarritoMenuItem);

        EliminarCarritoMenuItem.setMnemonic('y');
        EliminarCarritoMenuItem.setText("Eliminar");
        EliminarCarritoMenuItem.addActionListener(this::EliminarCarritoMenuItemActionPerformed);
        carritoMenu.add(EliminarCarritoMenuItem);

        menuBar.add(carritoMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarProductosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductosMenuItemActionPerformed
        if(actualizarProductoView == null || !actualizarProductoView.isVisible()){    
            actualizarProductoView = new ActualizarProductoView();
            productoController = new ProductoController(actualizarProductoView);
            actualizarProductoView.setVisible(true);
            desktopPane.add(actualizarProductoView);            
        }
    }//GEN-LAST:event_ActualizarProductosMenuItemActionPerformed

    private void EliminarCarritoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCarritoMenuItemActionPerformed
        
    }//GEN-LAST:event_EliminarCarritoMenuItemActionPerformed

    private void BuscarProductosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProductosMenuItemActionPerformed
        if(buscarProductoView == null || !buscarProductoView.isVisible()){    
           buscarProductoView = new BuscarProductoView();
           productoController = new ProductoController(buscarProductoView);
           buscarProductoView.setVisible(true);
           desktopPane.add(buscarProductoView);            
        }
    }//GEN-LAST:event_BuscarProductosMenuItemActionPerformed

    private void CrearProductosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProductosMenuItemActionPerformed
        if(crearProductoView == null || !crearProductoView.isVisible()){    
           crearProductoView = new CrearProductoView();
           productoController = new ProductoController(crearProductoView);
           crearProductoView.setVisible(true);
           desktopPane.add(crearProductoView);            
        }
        
    }//GEN-LAST:event_CrearProductosMenuItemActionPerformed

    private void EliminarProductosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductosMenuItemActionPerformed
        if(eliminarProductoView == null || !eliminarProductoView.isVisible()){    
           eliminarProductoView = new EliminarProductoView();
           productoController = new ProductoController(eliminarProductoView);
           eliminarProductoView.setVisible(true);
           desktopPane.add(eliminarProductoView);            
        }
    }//GEN-LAST:event_EliminarProductosMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarProductosMenuItem;
    private javax.swing.JMenuItem AgregarCarritoMenuItem;
    private javax.swing.JMenuItem BuscarProductosMenuItem;
    private javax.swing.JMenuItem CrearProductosMenuItem;
    private javax.swing.JMenuItem EliminarCarritoMenuItem;
    private javax.swing.JMenuItem EliminarProductosMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu carritoMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productosMenu;
    // End of variables declaration//GEN-END:variables

}
